package com.group5.studentportalbackend.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Entity
@Data
@EqualsAndHashCode
public class Student {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true)
    private String studentID;

    @Column(unique = true)
    private String email;
    private String firstName;
    private String lastName;
    
    private String PIN;
    private String sex;
    private String phoneNumber;
    private String level;
    private String hallOfResidence;
    private String guardianPhoneNumber;
    private String department;

    // Constructors, getters, setters, and other methods are automatically generated by Lombok.
}
